name = "pages-seo"
compatibility_date = "2026-05-18"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "my-royal-bath-d1"
database_id = "cba78c26-c661-429a-84f8-0927a0cfc36e"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "my-royal-bath-r2"

[ai]
binding = "AI"
